#!/bin/bash

# vezmi ip ze sloupecku SRC=11 TRG=12

ipsrc="$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' <<< $(awk '{print $11}' "/var/log/iptables.log"))"

# serad je do sloupecku
while IFS= read -r line
do
	iplist+=$line$'\n'
done < <(printf '%s\n' "$ipsrc")

# vyrad dupkikaty a setrid
ipsorted="$(sort <<< $iplist |uniq -u)"

# vypisuj informace do consolw a soubor logu z whois po jednom radku
while IFS= read -r line2
do
	echo $line2,\
	$(whois $line2 |grep -iE ^netname: | awk '{print $2}'),\
	$(whois $line2 |grep -iE ^country: | awk '{print $2}')\
	2>&1 | tee -a "/var/log/ipdos.log"
done < <(printf '%s\n' "$ipsorted")
