#!/bin/bash

# tak ip from collumn SRC=11 TRG=12

ipsrc="$(grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' <<< $(awk '{print $11}' "/var/log/iptables.log"))"

# sort to column
while IFS= read -r line
do
	iplist+=$line$'\n'
done < <(printf '%s\n' "$ipsrc")

# delete duplicates and sort
ipsorted="$(sort <<< $iplist |uniq -u)"

# echoing to user
while IFS= read -r line2
do
	echo $line2,\
	$(whois $line2 |grep -iE ^netname: | awk '{print $2}'),\
	$(whois $line2 |grep -iE ^country: | awk '{print $2}')\
	2>&1 | tee -a "/var/log/ipdos.log"
done < <(printf '%s\n' "$ipsorted")
